#ifndef __GUIMyFrame1__
#define __GUIMyFrame1__

/**
 * @file
 * Subclass of MyFrame1, which is generated by wxFormBuilder.
 */

#include "GUI.h"

 //// end generated include

#include <wx/dcmemory.h>
#include <wx/dcclient.h>
#include <wx/dcbuffer.h>
#include <wx/msgdlg.h>
#include <wx/wxprec.h>
#include <wx/wx.h> //OnQuit()
#include <wx/menu.h> //menu

struct Kwadrat
{
	Kwadrat() {}
	Kwadrat(wxBitmap im, int i, int j) : image{ im }, x{ i }, y{ j } {}

	//obraz
	wxBitmap image;

	//wspólrzędne
	int x;
	int y;
};

/** Implementing MyFrame1 */
class GUIMyFrame1 : public MyFrame1
{
public:
	/** Constructor */
	GUIMyFrame1(wxWindow* parent);

	void OnQuit(wxCommandEvent& event);	//quit event
	void OnNewGame(wxCommandEvent& event);	//quit event

	//funkcje obslugujace eventy
	void ssize(wxSizeEvent& event);
	void Timer1_Timer(wxTimerEvent& e);
	void hhh(wxKeyEvent& event);


	void get_started();	//zaczynamy liczyć czas

	//zapisujemy wektor w którym będa już poukladane elementy
	std::vector<Kwadrat> v;

	//// end generated class members
	void Repaint();

	~GUIMyFrame1()
	{
		delete timer;
	}

	//tekst przedstawiajacy czas
	wxStaticText* WxStaticText1;

	//menu
	wxMenuBar *menubar;
	wxMenu *file;
	wxMenu *imp;
	wxMenuItem *quit;
	wxMenuItem *newGame;

	//timer
	wxTimer* timer;

	wxImage Img_Org;	// tu bedzie przechowywany oryginalny obrazek
	wxImage Img_Cpy;	// wszystkie zmiany będa wykonywane na tej kopii obrazka
	wxImage tmp;		//tymczasowy obrazek

	int height;
	int width;
	int shiftAmount;

	//time as second-to check a difference
	wxDateTime started;
	int sec;
	int now_sec;

	//to sa nasze male elementy
	//bok kwadratu

	int x;	//użytkownik podaje dlugość x
	int y;	//wyliczony automatycznie
	int l;

	wxImage images[10][15];
	std::vector<Kwadrat> kwadraty;

	/* Private member functions for initialization and drawing
	void InitializeMenuBar();
	void InitializeTimer();
	void InitializeImage();
	void InitializeStaticText();

	void UpdateTimer();
	void DrawBackground(wxDC& dc);
	void DrawKwadraty(wxDC& dc);*/
};

#endif // __GUIMyFrame1__