#ifndef __GUIMyFrame1__
#define __GUIMyFrame1__

/**
@file
Subclass of MyFrame1, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include

//#include <wx/filedlg.h>
#include <wx/dcmemory.h>
#include <wx/dcclient.h>
#include <wx/dcbuffer.h>
//#include <wx/colourdata.h>
//#include <wx/colordlg.h>
#include <wx/msgdlg.h>
#include <wx/wxprec.h>

class Kwadrat
{

public:
	Kwadrat(){}
	Kwadrat(wxBitmap im,int i,int j):image{im},x{i},y{j}
	{}
	//obraz
	wxBitmap image;
	//wspó³rzêdne
	int x;
	int y;
};
/** Implementing MyFrame1 */
class GUIMyFrame1 : public MyFrame1
{
	
	public:
		wxStaticText* WxStaticText1;
		//funkcje obs³uguj¹ce eventy
		void ssize(wxSizeEvent& event);
		void Timer1_Timer(wxTimerEvent& e);
		void hhh(wxKeyEvent& event);
	
		//start game
		wxDateTime started;
		//time as second-to check a difference
		int sec;
		int now_sec;
		//zaczynamy liczyæ czas
		void get_started();
		//data które kawa³ki maj¹ byæ zamalowane-narazie nie u¿ywamy
		//int Data[300][300];
		//to s¹ nasze ma³e elementy
		wxImage images[10][15];
		//zapisujemy wektor w którym bêd¹ ju¿ pouk³adane elementy
		std::vector <Kwadrat> v;
		wxTimer *timer;
		/** Constructor */
		GUIMyFrame1( wxWindow* parent );
	//// end generated class members
		void Repaint();
		void Repaint_left();
		~GUIMyFrame1()
		{
			delete timer;
		}
  wxImage Img_Org, // tu bedzie przechowywany oryginalny obrazek
   Img_Cpy,        // wszystkie zmiany beda wykonywane na tej kopii obrazka
   tmp;       // tu bedzie przechowywana maska
  int height, width;
  int l;//w lewo lub w prawo wiêcej
};

#endif // __GUIMyFrame1__
